name: Mantain database active

on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  send-heartbeat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install dotenv mysql2
      - run: node ./wake.js