name: Mantain database active

on:
  schedule:
    - cron: '25 */2 * * *'

jobs:
  heartbeat:
    name: Heartbeat
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./heartbeat