name: Heartbeat cron-job
run-name: Mantain database alive

on:
  [push]
  # schedule:
  #   - cron: "25 */2 * * *"

jobs:
  heartbeat:
    name: Connect to remote and send heartbeat
    runs-on: ubuntu-latest
    env:
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PWD: ${{ secrets.DATABASE_PWD }}
    steps:
      - uses: actions/checkout@v3
      - name: Connect and execute
      - run: mysql -h ${{ secrets.DATABASE_HOST }} -u ${{ secrets.DATABASE_USER }} -p${{ secrets.DATABASE_PWD }} --ssl-mode=VERIFY_IDENTITY --ssl-ca=/etc/ssl/certs/ca-certificates.crt -e "source heartbeat/heartbeat.sql";
