name: Mantain database active

on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
        run: npm install dotenv mysql2
        run: node ./wake.js